### ISSUE TITLE
serialization errors (maybe originating in Vaadin internal classes?)

### ISSUE THREAD

**Issue by jorgheymans** [vaadin/kubernetes-kit#135]
Hi,

Eager to try out the improvements made in #131 , i ran the improved serialization debugger on our application. I am happy to report that even on our largest of pages, the serde debug works now and it works fast enough that it's useful. Big thanks to @mcollovati ! 

I managed to correct several issues with non-serializable lambda's in our code, but am left with 2 stacktraces that i cannot solve as there is no mention of any of our application packages. Does this mean there are some Vaadin internals not serializable?

```
ERRORS DURING SERIALIZATION/DESERIALIZATION PROCESS:
====================================================
DESERIALIZATION_FAILED: ReflectiveOperationException during deserialization

DESERIALIZATION STACK. Process failed at depth 9
	- object (class "java.io.ObjectStreamClass")
	- field (class "java.lang.invoke.SerializedLambda", name: "capturedArgs", type: "class [Ljava.lang.Object;")
	- object (class "java.lang.invoke.SerializedLambda", SerializedLambda[capturingClass=class com.vaadin.flow.component.internal.UIInternals, functionalInterfaceMethod=com/vaadin/flow/shared/Registration.remove:()V, implementation=invokeStatic com/vaadin/flow/component/internal/UIInternals.lambda$addListener$3630f8ab$1:(Ljava/util/List;Ljava/lang/Object;)V, instantiatedMethodType=()V, numCaptured=2])
	- field (class "com.vaadin.flow.spring.scopes.VaadinRouteScope$NavigationListener", name: "afterNavigationListener", type: "interface com.vaadin.flow.shared.Registration")
	- object (class "com.vaadin.flow.spring.scopes.VaadinRouteScope$NavigationListener", com.vaadin.flow.spring.scopes.VaadinRouteScope$NavigationListener@6fcb631d)
	- custom writeObject data (class "java.util.HashMap")
	- object (class "java.util.HashMap", {com.vaadin.flow.spring.scopes.VaadinRouteScope$NavigationListener=com.vaadin.flow.spring.scopes.VaadinRouteScope$NavigationListener@6fcb631d})
	- field (class "com.vaadin.flow.server.Attributes", name: "attributes", type: "class java.util.HashMap")
	- object (class "com.vaadin.flow.server.Attributes", com.vaadin.flow.server.Attributes@57bbb20e)
	- field (class "com.vaadin.flow.component.Component", name: "attributes", type: "class com.vaadin.flow.server.Attributes")
	- object (class "com.vaadin.flow.component.UI", com.vaadin.flow.component.UI@2111b80e)
	- custom writeObject data (class "java.util.HashMap")
	- object (class "java.util.HashMap", {0=com.vaadin.flow.component.UI@2111b80e})
	- custom writeObject data (class "com.vaadin.flow.server.VaadinSession")
	- object (class "com.vaadin.flow.spring.SpringVaadinSession", com.vaadin.flow.spring.SpringVaadinSession@1669793b)
	- custom writeObject data (class "java.util.HashMap")
	- root object (class "java.util.HashMap", {com.vaadin.flow.server.VaadinSession.springServlet=com.vaadin.flow.spring.SpringVaadinSession@1669793b, springServlet.lock=java.util.concurrent.locks.ReentrantLock@1256ff2e[Unlocked], clusterKey=823528b6-878c-4a76-95c6-af75fa88be7d_SOURCE:EE20EFC2B8EF2AB2363F0190BE0CE08C, SPRING_SECURITY_CONTEXT=SecurityContextImpl 
``` 

and this one (presumably related to the error above?), note the useful part is completely at the bottom

```
.SerializationDebugRequestHandler : Test session deserialization failed

java.io.InvalidObjectException: ReflectiveOperationException during deserialization
	at java.base/java.lang.invoke.SerializedLambda.readResolve(SerializedLambda.java:280)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor159.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1190)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2266)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733)
	at java.base/java.io.ObjectInputStream$FieldValues.<init>(ObjectInputStream.java:2606)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2457)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2257)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733)
	at java.base/java.io.ObjectInputStream.readArray(ObjectInputStream.java:2157)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1721)
	at java.base/java.io.ObjectInputStream$FieldValues.<init>(ObjectInputStream.java:2606)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2457)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2257)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733)
	at java.base/java.io.ObjectInputStream$FieldValues.<init>(ObjectInputStream.java:2606)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2457)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2257)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:509)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:467)
	at java.base/java.util.ArrayList.readObject(ArrayList.java:899)
...
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1100)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2423)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2257)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:509)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:467)
	at com.vaadin.kubernetes.starter.sessiontracker.serialization.TransientInjectableObjectInputStream.readWithTransients(TransientInjectableObjectInputStream.java:160)
	at com.vaadin.kubernetes.starter.sessiontracker.SessionSerializer.doDeserialize(SessionSerializer.java:467)
	at com.vaadin.kubernetes.starter.sessiontracker.SessionSerializer.deserialize(SessionSerializer.java:211)
	at com.vaadin.kubernetes.starter.sessiontracker.serialization.debug.SerializationDebugRequestHandler.tryDeserialize(SerializationDebugRequestHandler.java:283)
	at com.vaadin.kubernetes.starter.sessiontracker.serialization.debug.SerializationDebugRequestHandler.serializeAndDeserialize(SerializationDebugRequestHandler.java:218)
	at com.vaadin.kubernetes.starter.sessiontracker.serialization.debug.SerializationDebugRequestHandler$Runner.accept(SerializationDebugRequestHandler.java:177)
	at com.vaadin.kubernetes.starter.sessiontracker.serialization.debug.SerializationDebugRequestHandler$Filter.doFilter(SerializationDebugRequestHandler.java:197)
	at jakarta.servlet.http.HttpFilter.doFilter(HttpFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:108)
	at org.springframework.security.web.FilterChainProxy.lambda$doFilterInternal$3(FilterChainProxy.java:231)
	at org.springframework.security.web.ObservationFilterChainDecorator$FilterObservation$SimpleFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:479)
	at org.springframework.security.web.ObservationFilterChainDecorator$AroundFilterObservation$SimpleAroundFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:340)
	at org.springframework.security.web.ObservationFilterChainDecorator.lambda$wrapSecured$0(ObservationFilterChainDecorator.java:82)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:128)
	at org.springframework.security.web.access.intercept.AuthorizationFilter.doFilter(AuthorizationFilter.java:100)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:179)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter.doFilter(AbstractPreAuthenticatedProcessingFilter.java:150)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:117)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:82)
	at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:69)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$AroundFilterObservation$SimpleAroundFilterObservation.lambda$wrap$0(ObservationFilterChainDecorator.java:323)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:224)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:233)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:113)
	at org.springframework.web.servlet.handler.HandlerMappingIntrospector.lambda$createCacheFilter$3(HandlerMappingIntrospector.java:195)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:113)
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:74)
	at org.springframework.security.config.annotation.web.configuration.WebMvcSecurityConfiguration$CompositeFilterChainProxy.doFilter(WebMvcSecurityConfiguration.java:230)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.GeneratedMethodAccessor273.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.lang.invoke.SerializedLambda.readResolve(SerializedLambda.java:278)
	... 825 common frames omitted
Caused by: java.lang.ClassCastException: class java.lang.invoke.SerializedLambda cannot be cast to class com.vaadin.flow.data.provider.DataGenerator (java.lang.invoke.SerializedLambda is in module java.base of loader 'bootstrap'; com.vaadin.flow.data.provider.DataGenerator is in unnamed module of loader 'app')
	at com.vaadin.flow.data.provider.CompositeDataGenerator.$deserializeLambda$(CompositeDataGenerator.java:39)
	... 829 common frames omitted
```

**Comment by mcollovati** [comment]
The two traces could be somehow related.
Do you have a `TreeGrid` in your application? Is it perhaps `@RouteScope`d or contained in a `@RouteScope` component?

`CompositeDataGenerator` retains a list of `DataGenerator`s. At least one of those is given as a lambda that probably has a self-reference issue.

Unfortunately, I'm currently not able to reproduce.

**Comment by mcollovati** [comment]
If you can build your own KIT version, you can try to add the following snippet in `Job.deserializationFailed()` and see if it can provide more information

```
    void deserializationFailed(Exception ex) {
        outcome.add(Outcome.DESERIALIZATION_FAILED);
        log(CATEGORY_ERRORS,
                Outcome.DESERIALIZATION_FAILED.name() + ": " + ex.getMessage());

        // -------> CODE TO ADD
        if (ex instanceof InvalidObjectException) {
            Throwable cause = ex.getCause();
            if (cause instanceof ReflectiveOperationException) {
                cause = cause.getCause();
                if (cause instanceof InvocationTargetException) {
                    cause = cause.getCause();
                    if (cause instanceof ClassCastException castException) {
                        ex = castException;
                    }
                }
            }
        }
        // -------> END CODE TO ADD

        if (ex instanceof ClassCastException
                && ex.getMessage().contains(SerializedLambda.class.getName())
                && !serializedLambdaMap.isEmpty()) {
        ....
```

**Comment by jorgheymans** [comment]
Thanks ! I had to tweak it a bit  to get the full serialization error stacktrace:

```
        // -------> CODE TO ADD
        if (ex instanceof InvalidObjectException) {
            Throwable cause = ex.getCause();
            if (cause instanceof ReflectiveOperationException) {
                cause = cause.getCause();
                if (cause instanceof ClassCastException castException) {
                    cause = cause.getCause();
                    ex = castException;
                }
            }
        }
        // -------> END CODE TO ADD
```
Here is the initial part of the stacktrace, the full one if needed i'll send by mail.

```
ERRORS DURING SERIALIZATION/DESERIALIZATION PROCESS:
====================================================
DESERIALIZATION_FAILED: ReflectiveOperationException during deserialization

SERIALIZED LAMBDA CLASS CAST EXCEPTION BEST CANDIDATES:
=======================================================
	SerializedLambda[capturingClass=class com.vaadin.flow.data.renderer.LitRenderer, functionalInterfaceMethod=com/vaadin/flow/data/provider/DataGenerator.generateData:(Ljava/lang/Object;Lelemental/json/JsonObject;)V, implementation=invokeVirtual com/vaadin/flow/data/renderer/LitRenderer.lambda$createDataGenerator$bbb7bb69$1:(Ljava/lang/Object;Lelemental/json/JsonObject;)V, instantiatedMethodType=(Ljava/lang/Object;Lelemental/json/JsonObject;)V, numCaptured=1]
	- custom writeObject data (class "java.util.HashSet")
	- object (class "java.util.LinkedHashSet", [com.vaadin.flow.component.grid.Grid$$Lambda$3287/0x0000000101765558@354ea026, com.vaadin.flow.component.grid.Grid$$Lambda$3288/0x00000001017657d8@752a8723, com.vaadin.flow.component.grid.Grid$$Lambda$3289/0x0000000101765a58@10e4a366, com.vaadin.flow.component.grid.Grid$$Lambda$3290/0x0000000101765cd8@1e461d96, com.vaadin.flow.component.grid.Grid$$Lambda$3291/0x0000000101765f58@5e49d1e8, com.vaadin.flow.component.grid.Grid$$Lambda$3292/0x00000001017661d8@7f7b469d, com.vaadin.flow.component.grid.Grid$DetailsManager@4ab13587, com.vaadin.flow.component.grid.ColumnPathRenderer$SingleValueProviderRendering$$Lambda$3314/0x000000010176e268@58748f62, com.vaadin.flow.component.grid.Grid$SelectionMode$1@289459cb, com.vaadin.flow.data.renderer.LitRenderer$$Lambda$3324/0x000000010176dbf0@748937c1, com.vaadin.flow.data.renderer.LitRenderer$$Lambda$3324/0x000000010176dbf0@edc13cd])
	- field (class "com.vaadin.flow.data.provider.CompositeDataGenerator", name: "dataGenerators", type: "interface java.util.Set")
	- object (class "com.vaadin.flow.data.provider.CompositeDataGenerator", com.vaadin.flow.data.provider.CompositeDataGenerator@7290550b)
	- field (class "com.vaadin.flow.data.provider.DataCommunicator", name: "dataGenerator", type: "interface com.vaadin.flow.data.provider.DataGenerator")
	- object (class "com.vaadin.flow.data.provider.DataCommunicator", com.vaadin.flow.data.provider.DataCommunicator@7e42499)
	- element of array (index: 0)
	- array (class "[Ljava.lang.Object;", size: 1)
	- field (class "java.lang.invoke.SerializedLambda", name: "capturedArgs", type: "class [Ljava.lang.Object;")
	- object (class "java.lang.invoke.SerializedLambda", SerializedLambda[capturingClass=class com.vaadin.flow.data.provider.DataCommunicator, functionalInterfaceMethod=com/vaadin/flow/server/Command.execute:()V, implementation=invokeVirtual com/vaadin/flow/data/provider/DataCommunicator.handleAttach:()V, instantiatedMethodType=()V, numCaptured=1])
	- custom writeObject data (class "java.util.ArrayList")
	- object (class "java.util.ArrayList", [com.vaadin.flow.data.provider.DataCommunicator$$Lambda$3115/0x000000010172d7a8@2deb5961, com.vaadin.flow.internal.StateNode$1@2aa59fc7, com.vaadin.flow.internal.StateNode$1@2ee4eb00, com.vaadin.flow.internal.StateNode$1@33fa16b3, com.vaadin.flow.internal.StateNode$1@44ad61fc, com.vaadin.flow.internal.StateNode$1@42709509])
	- field (class "com.vaadin.flow.internal.StateNode", name: "attachListeners", type: "interface java.util.List")
	- object (class "com.vaadin.flow.internal.StateNode", com.vaadin.flow.internal.StateNode@2f52747e)
	- field (class "com.vaadin.flow.dom.Node", name: "node", type: "class com.vaadin.flow.internal.StateNode")
	- object (class "com.vaadin.flow.dom.Element", <vaadin-grid multi-sort multi-sort-priority="prepend" theme="row-stripes" slot="grid" style="max-height:200.0px">
 <vaadin-grid-column></vaadin-grid-column>
 <vaadin-grid-column></vaadin-grid-column>
 <vaadin-grid-column></vaadin-grid-column>
</vaadin-grid>)
	- field (class "com.vaadin.flow.component.Component", name: "element", type: "class com.vaadin.flow.dom.Element")
	- object (class "com.vaadin.flow.component.crud.CrudGrid", com.vaadin.flow.component.crud.CrudGrid@75af707c)
	- element of array (index: 0)
	- array (class "[Ljava.lang.Object;", size: 1)
	- field (class "java.lang.invoke.SerializedLambda", name: "capturedArgs", type: "class [Ljava.lang.Object;")
	- object (class "java.lang.invoke.SerializedLambda", SerializedLambda[capturingClass=class com.vaadin.flow.component.grid.Grid, functionalInterfaceMethod=com/vaadin/flow/data/provider/DataProviderListener.onDataChange:(Lcom/vaadin/flow/data/provider/DataChangeEvent;)V, implementation=invokeVirtual com/vaadin/flow/component/grid/Grid.lambda$handleDataProviderChange$78e8296$1:(Lcom/vaadin/flow/data/provider/DataChangeEvent;)V, instantiatedMethodType=(Lcom/vaadin/flow/data/provider/DataChangeEvent;)V, numCaptured=1])
	- field (class "com.vaadin.flow.data.provider.AbstractDataProvider$1", name: "val$listener", type: "interface com.vaadin.flow.data.provider.DataProviderListener")
	- object (class "com.vaadin.flow.data.provider.AbstractDataProvider$1", com.vaadin.flow.data.provider.AbstractDataProvider$1@d3c45d8)
	- field (class "com.vaadin.flow.data.provider.AbstractDataProvider$DataListenerWrapper", name: "listener", type: "interface com.vaadin.flow.function.SerializableConsumer")
	- object (class "com.vaadin.flow.data.provider.AbstractDataProvider$DataListenerWrapper", com.vaadin.flow.data.provider.AbstractDataProvider$DataListenerWrapper@ede8fdc)
	- custom writeObject data (class "java.util.ArrayList")
	- object (class "java.util.ArrayList", [com.vaadin.flow.data.provider.AbstractDataProvider$DataListenerWrapper@ede8fdc, com.vaadin.flow.data.provider.AbstractDataProvider$DataListenerWrapper@4f77d325])
	- custom writeObject data (class "java.util.HashMap")
	- object (class "java.util.HashMap", {class com.vaadin.flow.data.provider.DataChangeEvent=[com.vaadin.flow.data.provider.AbstractDataProvider$DataListenerWrapper@ede8fdc, com.vaadin.flow.data.provider.AbstractDataProvider$DataListenerWrapper@4f77d325]})
	- field (class "com.vaadin.flow.data.provider.AbstractDataProvider", name: "listeners", type: "class java.util.HashMap")
```

**Comment by mcollovati** [comment]
So, potentially the cause is in a `LitRenderer`, but I'm still unsure if the problem resides in the `LitRender` class or in the application code, since I'm unable to reproduce the issue adding a simple render to a grid.

Could you please share how the `LitRenderer` is configured in your application?

**Comment by jorgheymans** [comment]
We don't have any direct mention of LitRenderer in our application, it must be coming via one of the Vaadin components (GridPro?) Further down the stacktrace, there is mention of one of our application classes, i'll try and do some more experimenting to see if it's directly related or not.

**Comment by mcollovati** [comment]
@jorgheymans I can reproduce the issue with the provided snippet. Thanks a lot

**Comment by mcollovati** [comment]
It can be reproduced on a normal `Grid` by adding 

```
grid.addColumn(new BasicRenderer<>(ValueProvider.identity()) {
});
```

**Comment by jorgheymans** [comment]
Does this mean a fix needs to be done in flow-components, or we can solve the issue locally in our application?

**Comment by mcollovati** [comment]
I'm currently investigating to find the root cause.

**Comment by mcollovati** [comment]
The self-reference should be the following

```
Grid.dataGenerators[] (CompositeDataGenerator)
	-> DataGenerator lambda obtained from TextRenderer < BasicRenderer < ComponentRenderer < LitRenderer
       /|\	-> ComponentRenderer.container (Element)
	|		-> Element.parent
	|			-> Element.features
	|				-> ComponentMapping.component
	|					-> Grid.Column
	|						-> Grid.Column.columnDataGeneratorRegistration (Registration lambda)
	|							-> capturedArgs:
	|								CompositeDataGenerator: dataGenerators[] null as it is currently deserializing
	--------------------------------------------------------------- SerializedLambda (the LitRenderer.DataGenerator currently deserializing)
```

**Comment by jorgheymans** [comment]
Thinking about this, it does make me wonder if the current serialization approach (jdk serde) is the right one, as particular combinations of individually serializable objects can make the object tree non-serializable. Are there guards setup in the flow testing suite that detect this early?    

Do other serde frameworks like gson, kryo etc suffer from the same limitations? I see in the closed issues that these have been investigated before but were discarded.
